- name: Install Shibboleth centralized Discovery Service for UbuntuNet Alliance
  hosts: cds
  become: True

  roles:
    - shibboleth_cds

  handlers:
    - name: restart tomcat
      service: name=tomcat{{ tomcat_version }} state=restarted