- name: Install Apache
  apt: name=apache2 update_cache=yes cache_valid_time=36000

- name: Copy index.html page
  template: >
    src=index.html.j2
    dest=/var/www/html/index.html
  notify: restart apache